language: java
jdk:
- oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw -Dspring.profiles.active=dev -Dmaven.javadoc.skip=true clean install -B -V
